### ISSUE TITLE
Case sensitivite filesystems and pycrypto dependency break module

### ISSUE THREAD

**Issue by tsujamin** [python-otr/pure-python-otr#65]
I am unable to use `potr` on my Macbook due to case insensitivity but preserving nature of HFS+.

```
File "/usr/local/lib/python2.7/site-packages/potr/__init__.py", line 21, in <module>
from potr import context
File "/usr/local/lib/python2.7/site-packages/potr/context.py", line 43, in <module>
from potr import crypt
File "/usr/local/lib/python2.7/site-packages/potr/crypt.py", line 25, in <module>
from potr.compatcrypto import SHA256, SHA1, SHA1HMAC, SHA256HMAC, \
File "/usr/local/lib/python2.7/site-packages/potr/compatcrypto/__init__.py", line 21, in <module>
from potr.compatcrypto.pycrypto import *
File "/usr/local/lib/python2.7/site-packages/potr/compatcrypto/pycrypto.py", line 18, in <module>
from Crypto import Cipher
ImportError: No module named Crypto
```

The issue appears to be caused by the importing of `pycrypto` in the uppercase form in the following [lines](https://github.com/python-otr/pure-python-otr/blob/master/src/potr/compatcrypto/pycrypto.py#L18-L24)

```python
from Crypto import Cipher
from Crypto.Hash import SHA256 as _SHA256
from Crypto.Hash import SHA as _SHA1
from Crypto.Hash import HMAC as _HMAC
from Crypto.PublicKey import DSA
from Crypto.Random import random
```

It appears that when `pip` installs `pycrypto`, it names the module in the lower-cased convention such that the upper-case variant, used by `potr`, cannot be imported

```
>>> import Crypto
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named Crypto
>>> import crypto
>>>
```

For the moment I've renamed my local `pycrypto` to the upper-case, and I was going to submit a trivial PR to lower-case the imports in `potr` but I'm not well versed enough on running Python on other platforms to know whether this might introduce new issues.

I'm also not sure if this is technically a `potr` problem of a `pycrypto` problem, so I'm happy to move this issue if required.

**Comment by koolfy** [comment]
Hello,

Thanks for the report !

I don't think potr was properly tested around a OS X environment, so tread with care, and report any anomalies you might find.

I'll test the lowercase in other environments this evening and get back to you.
I don't have a OS X for testing though, so stay around for confirming the resolution soon :)

**Comment by koolfy** [comment]
Ok, this is going to be a little less trivial than I thought :p

  Python 2.7.9 (default, Mar  8 2015, 00:52:26) 
  [GCC 4.9.2] on linux2
  Type "help", "copyright", "credits" or "license" for more information.
  >>> import crypto
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
  ImportError: No module named crypto
  >>> import Crypto
  >>> 


But nothing we can't handle.


Can anyone try it on windows and see which one it is?

**Comment by azrdev** [comment]
@koolfy handling this should be something like
~~~python
try:
  import crypto
except ImportError:
  import Crypto as crypto

**Comment by koolfy** [comment]
Yes, that's what I had in mind :)
I'll make the fix in a few.

Still curious about which one windows would accept, if not both.

**Comment by afflux** [comment]
I'd argue this is a bug in pycrypto or python on HFS+. The module name is ```Crypto```.

**Comment by tsujamin** [comment]
@koolfy as far as I can recall, NTFS suffers the same issue as HFS+ (Case-Insensitive but Preserving). As to whether it's a pycrypto bug or not, I'm not sure as they don't necessarily have a method to control the casing of their module? I'd be interested to see how packages usually deal with this though too.

**Comment by koolfy** [comment]
So, I just pushed an ugly fix, while we discuss the issue.

I didn't test it, as I don't currently have case-stupid^W mac OSX or Windows machines at hand at the moment.
So I need you guys to check it out and tell me how it works on the three environments.

Linux should be fine, but I tested it in a hurry, so again, don't trust me on this.

It's branching from the staging branch, and I won't merge it to staging until

1) I have confirmation that this actually does *work*
2) I have confirmation that there isn't a better way to fix this (I'd gladly open a bug report somewhere else so we don't have to deal with this, but I don't think we'll get around it. It's not pretty but it doesn't break much)

I'll have a look at how other packages deal with this, but I suspect I'll find the same try except.


Thoughts?

**Comment by tsujamin** [comment]
Looking good from OS X

**Comment by koolfy** [comment]
Great news.
I'm not sure I'll wait for a windows confirmation, we could be waiting for quite some time :p

I'll have a look around other projects, if I don't find something better I'll merge to staging.

**Comment by koolfy** [comment]
Merged this to Staging, I'm closing this for now, don't hesitate to reopen if something breaks or a better approach exists

**Comment by afflux** [comment]
I still don't get why this needs to be handled. The package name is Crypto, HFS+ is case-preserving -- AFAIK, a user had to actively screw things up if they wanted to install pycrypto with lowercase filenames (maybe you hit dlitz/pycrypto#156?). Then again this fix doesn't really hurt, so w/e.
